name: Publish Docker image to GitHub Packages

on:
  release:
    types: [created]

jobs:
  publish:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Publish jib container image to GitHub Packages
      run: mvn compile jib:build
      env:
        REGISTRY: ghcr.io
        IMAGE_NAME: ${{ github.repository }}
        REGISTRY_USERNAME: ${{ github.actor }}
        REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}	